# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 10:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watch_time', models.IntegerField()),
                ('value', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('date_creation', models.DateTimeField(default=datetime.datetime(2017, 11, 1, 10, 10, 24, 627662, tzinfo=utc))),
                ('watched_type', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=1)),
                ('city_id', models.IntegerField()),
                ('coordinates', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('desc', models.CharField(max_length=10000)),
                ('date_creation', models.DateTimeField(blank=True, null=True)),
                ('location', models.IntegerField(blank=True, null=True)),
                ('asgie_id', models.IntegerField(blank=True, null=True)),
                ('asgie_title_pt', models.CharField(max_length=500)),
                ('tokens', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='majordomo.User'),
        ),
        migrations.AddField(
            model_name='rating',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='majordomo.Video'),
        ),
    ]
