# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majordomo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='date_creation',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='video',
            name='asgie_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='date_creation',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='video',
            name='desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='video',
            name='location',
            field=models.CharField(blank=True, max_length=1),
        ),
    ]
