# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-16 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majordomo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='location',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
