# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-16 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majordomo', '0002_auto_20180216_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='location',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
