# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majordomo', '0002_auto_20171101_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='location',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
