# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majordomo', '0003_auto_20171101_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='overall_rating_value',
            field=models.DecimalField(decimal_places=9, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='rating',
            name='rating_explicit',
            field=models.DecimalField(decimal_places=9, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='rating',
            name='rating_implicit',
            field=models.DecimalField(decimal_places=9, default=0, max_digits=10),
        ),
    ]
