# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majordomo', '0004_auto_20171101_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asgie',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250, unique=True)),
                ('title_pt', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=100)),
            ],
        ),
    ]
