# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 17:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('majordomo', '0005_asgie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='asgie_id',
        ),
        migrations.RemoveField(
            model_name='video',
            name='asgie_title_pt',
        ),
        migrations.AddField(
            model_name='video',
            name='asgie',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='majordomo.Asgie'),
            preserve_default=False,
        ),
    ]
