# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 09:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('majordomo', '0007_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='city_id',
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='majordomo.City'),
            preserve_default=False,
        ),
    ]
